-- Copie e cole este código no SQL Editor do Supabase para criar as tabelas necessárias

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  registration_number TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  professional_category TEXT NOT NULL,
  hourly_rate REAL DEFAULT 0,
  must_change_password SMALLINT DEFAULT 1,
  is_admin SMALLINT DEFAULT 0,
  role_user TEXT DEFAULT 'USER',
  lotacao_fisica TEXT DEFAULT 'samu pvh'
);

CREATE TABLE IF NOT EXISTS extras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  type TEXT CHECK(type IN ('rural', 'urban')) NOT NULL,
  hours REAL NOT NULL,
  observations TEXT,
  start_time TEXT,
  end_time TEXT,
  is_sent SMALLINT DEFAULT 0,
  reason TEXT,
  month INTEGER NOT NULL,
  year INTEGER NOT NULL
);

-- Inserir dados iniciais
INSERT INTO users (name, registration_number, password, professional_category, hourly_rate, is_admin, role_user, lotacao_fisica, must_change_password)
VALUES 
  ('Administrador Principal', 'adm', 'admin', 'Administrativo', 0, 1, 'ADM', 'samu pvh', 1)
ON CONFLICT (registration_number) DO UPDATE SET password = 'admin', must_change_password = 1;
